import "./globals.css"
import type {Metadata} from "next"
import {Inter} from "next/font/google"
import {Hydrate, dehydrate} from "@tanstack/react-query"
import {QueryClient} from "@tanstack/query-core"
import {cache} from "react"
import Provider from "utils/Provider"

const inter = Inter({subsets: ["latin"]})
const getQueryClient = cache(() => new QueryClient())

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  const queryClient = getQueryClient()
  const dehydratedState = dehydrate(queryClient)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Hydrate state={dehydratedState}>{children}</Hydrate>
          <div id="portal" />
          <div id="portal-loading" />
        </Provider>
      </body>
    </html>
  )
}
